name: Maven Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
        include:
          - java: 8
            maven-args: "-Dcoveralls.repoToken=$COVERALLS_REPO_TOKEN coveralls:report"
          - java: 11
            maven-args: "-B sonar:sonar -Dsonar.projectKey=shakeelmuhammadyasir_library_management"
    
    name: Build with Java ${{ matrix.java }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      - name: Cache Maven and SonarCloud packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.sonar/cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn clean verify -Pjacoco ${{ matrix.maven-args }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

